name: '[Chore] Formatting'

on:
    push:
        branches:
            - dev
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * *' # Runs every day at midnight UTC

permissions:
    contents: write
    workflows: write

jobs:
    chore-prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  ref: dev

            - name: Install Prettier
              run: |
                  npm install -g prettier

            - name: Format JSON files using Prettier
              run: |
                  prettier --write .

            - name: Commit and push changes
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email "github-actions@users.noreply.github.com"
                  git add -A
                  if ! git diff --cached --quiet; then
                    git commit -m "[GH actions chore] format files with prettier"
                    git push origin HEAD:dev
                  else
                    echo "No changes to commit👍👍"
                  fi
